import { COMPANY } from "@/lib/company";
export interface CatalogItem {
  id: string;
  category: string;
  designation: string;
  unit: 'm²' | 'm.l.' | 'U' | 'Ens.' | 'Forfait' | 'h' | 'kg' | 'm³';
  unitPriceHT: number;
  tvaRate: 5.5 | 10 | 20;
  brandRef?: string;
  sourceDevis?: string;
}

export interface CatalogCategory {
  name: string;
  items: CatalogItem[];
}

/**
 * Base de Données des Prestations et Prix ERG Rénovation
 * Extraite directement des devis réels (Mr BAH - D00207, Mr Sebaouni - D0192, Soliko - D0192)
 */
export const ERG_COMPANY_INFO = {
  name: "ERG Rénovation",
  legalForm: COMPANY.legalForm,
  rcs: "RCS PARIS 818 676 652",
  siret: COMPANY.siret,
  address: COMPANY.address,
  phone1: "06 99 96 13 75",
  phone2: "09 80 93 84 18",
  email: "contact@erg-renovation.fr",
  website: "www.erg-renovation.fr",
  decennale: COMPANY.decennale,
  paymentSchedule: [
    { label: "Acompte début des travaux", percent: 30 },
    { label: "Réalisation 1/2 des travaux", percent: 30 },
    { label: "Réalisation 3/4 des travaux", percent: 30 },
    { label: "Solde à la fin des travaux (Réception)", percent: 10 },
  ],
};

export const ERG_PRICE_CATALOG: CatalogCategory[] = [
  {
    name: "DÉMOLITION & PRÉPARATION CHANTIER",
    items: [
      {
        id: "dem-01",
        category: "DÉMOLITION & PRÉPARATION CHANTIER",
        designation: "Protection de la zone d'intervention avec nettoyage quotidien de la zone d'intervention et des parties communes",
        unit: "Ens.",
        unitPriceHT: 150.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207 & D0192",
      },
      {
        id: "dem-02",
        category: "DÉMOLITION & PRÉPARATION CHANTIER",
        designation: "Dépose de toute la plomberie à partir des arrivées d'eau et de la salle de bain et cuisine",
        unit: "Ens.",
        unitPriceHT: 90.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "dem-03",
        category: "DÉMOLITION & PRÉPARATION CHANTIER",
        designation: "Dépose de toute l'ancienne installation électrique (cuisine, salle de bain, séjour, chambre)",
        unit: "Ens.",
        unitPriceHT: 150.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "dem-04",
        category: "DÉMOLITION & PRÉPARATION CHANTIER",
        designation: "Dépose du mur qui sépare actuellement la salle de bain (surface : 3m²)",
        unit: "Forfait",
        unitPriceHT: 250.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "dem-05",
        category: "DÉMOLITION & PRÉPARATION CHANTIER",
        designation: "Dépose de la dalle ou chape existante (salle de bain, cuisine, séjour - Surface : 10m²)",
        unit: "Forfait",
        unitPriceHT: 250.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "dem-06",
        category: "DÉMOLITION & PRÉPARATION CHANTIER",
        designation: "Dépose moquette et décapage de la colle (séjour, superficie : 50 m²)",
        unit: "Forfait",
        unitPriceHT: 950.0,
        tvaRate: 10,
        sourceDevis: "Devis D0192",
      },
      {
        id: "dem-07",
        category: "DÉMOLITION & PRÉPARATION CHANTIER",
        designation: "Mise à la décharge des gravats et évacuation déchetterie agréée BTP",
        unit: "Forfait",
        unitPriceHT: 850.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "dem-08",
        category: "DÉMOLITION & PRÉPARATION CHANTIER",
        designation: "Mise à la décharge des gravats (format réduit)",
        unit: "Forfait",
        unitPriceHT: 150.0,
        tvaRate: 10,
        sourceDevis: "Devis D0192",
      },
    ],
  },
  {
    name: "GROS ŒUVRE, PLÂTRERIE & CHAPE",
    items: [
      {
        id: "pla-01",
        category: "GROS ŒUVRE, PLÂTRERIE & CHAPE",
        designation: "Réalisation d'une chape allégée avec Film de protection sous-dalle polyéthylène T 150 Tet ferraillage compris Ragréage auto-lissant Weber P3 (surface sol salle de bain et entrée : 9,88m²)",
        unit: "Forfait",
        unitPriceHT: 980.0,
        tvaRate: 10,
        brandRef: "Weber P3",
        sourceDevis: "Devis D00207",
      },
      {
        id: "pla-02",
        category: "GROS ŒUVRE, PLÂTRERIE & CHAPE",
        designation: "Fourniture et mise en œuvre deux murs plaque de BA 13 monté sur une ossature métallique fixé de chaque côté, inclus bande de finition (salle de bain L130cm x L200cm x 250cm)",
        unit: "Forfait",
        unitPriceHT: 980.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "pla-03",
        category: "GROS ŒUVRE, PLÂTRERIE & CHAPE",
        designation: "Égalisation des irrégularités avec colle hydrofuge ou pose plaque de plâtre hydrofuge de type Plaque de BA 13 (salle de bain tous les murs surface 20,60m²)",
        unit: "Forfait",
        unitPriceHT: 340.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "pla-04",
        category: "GROS ŒUVRE, PLÂTRERIE & CHAPE",
        designation: "Fourniture et pose d'un doublage isolant phonique et thermique côté mur mitoyen Doublissimo Performance 3,8 m²·K/W ; 32 mW/m.K (surface : 4,34m x 2,50m)",
        unit: "Forfait",
        unitPriceHT: 780.0,
        tvaRate: 5.5,
        brandRef: "Placo Doublissimo",
        sourceDevis: "Devis D00207",
      },
    ],
  },
  {
    name: "ÉLECTRICITÉ & SÉCURITÉ",
    items: [
      {
        id: "elec-01",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "Fourniture et pose d'un tableau électrique 1 interrupteur différentiel 40A type AC, 1 interrupteur différentiel 40A type A, 12 disjoncteurs Schneider, encastrement des lignes et appareillage Schneider ODACE",
        unit: "Ens.",
        unitPriceHT: 1050.0,
        tvaRate: 10,
        brandRef: "Schneider Electric ODACE",
        sourceDevis: "Devis D00207",
      },
      {
        id: "elec-02",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "CUISINE ÉQUIPÉE : Prise 32A plaque, 20A four, 20A lave-vaisselle, 10A hotte, 4 prises 20A crédence, 20A frigo, 3 douilles normalisées (spot/réglette) avec interrupteur + douille plafonnier",
        unit: "Ens.",
        unitPriceHT: 910.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "elec-03",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "Fourniture et pose 5 Prises 16A 2P+T inclus deux appliques en douille normalisée commandées par deux va-et-vient (séjour)",
        unit: "Ens.",
        unitPriceHT: 750.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "elec-04",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "Fourniture et pose 4 prises 16A 2P+T, fourniture et pose une douille normalisée commandée par un inter simple allumage (chambre)",
        unit: "Ens.",
        unitPriceHT: 680.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "elec-05",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "Fourniture et pose une prise 16A 2P+T inclus sortie de câble meuble SDB + prise 20A+T pour machine à laver",
        unit: "Ens.",
        unitPriceHT: 450.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "elec-06",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "Fourniture et pose spots IP65 et spots IP44 SDB commandé par interrupteur + spot IP44 entrée (Pack 6 spots cuisine SYLDUO 3x270LM 3000K Blanc)",
        unit: "Ens.",
        unitPriceHT: 350.0,
        tvaRate: 10,
        brandRef: "SYLDUO 3x270LM",
        sourceDevis: "Devis D00207",
      },
      {
        id: "elec-07",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "Fourniture et pose Kit extra plat VMC simple flux autoréglable détection d'humidité SAUTER Agalina pour cuisine et salle de bain",
        unit: "U",
        unitPriceHT: 480.0,
        tvaRate: 10,
        brandRef: "SAUTER Agalina",
        sourceDevis: "Devis D00207",
      },
      {
        id: "elec-08",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "Fourniture et pose Chauffe-eau électrique plat horizontal/vertical SAUTER Guelma connecté 65l blanc (Réf 82973791 Leroy Merlin)",
        unit: "U",
        unitPriceHT: 980.0,
        tvaRate: 10,
        brandRef: "SAUTER Guelma 65L (Leroy Merlin)",
        sourceDevis: "Devis D00207",
      },
      {
        id: "elec-09",
        category: "ÉLECTRICITÉ & SÉCURITÉ",
        designation: "Fourniture et pose une prise 20A 2P+T pour alimentation chauffe-eau",
        unit: "U",
        unitPriceHT: 140.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
    ],
  },
  {
    name: "PLOMBERIE & SANITAIRES",
    items: [
      {
        id: "plo-01",
        category: "PLOMBERIE & SANITAIRES",
        designation: "Fourniture et application produit d'étanchéité Weber.sys protect sol et mur salle de bain",
        unit: "Forfait",
        unitPriceHT: 180.0,
        tvaRate: 10,
        brandRef: "Weber.sys protect",
        sourceDevis: "Devis D00207",
      },
      {
        id: "plo-02",
        category: "PLOMBERIE & SANITAIRES",
        designation: "Fourniture et pose des réseaux eau chaude eau froide en cuivre Ø14mm-16mm au départ de la gaine technique pour alimentation (douche, lavabo, évier, lave-linge, WC)",
        unit: "Ens.",
        unitPriceHT: 980.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "plo-03",
        category: "PLOMBERIE & SANITAIRES",
        designation: "Fourniture et pose des conduits de vidange en PVC Ø32-40-50mm vers colonnes d'évacuation (receveur, lavabo, évier, lave-linge, lave-vaisselle)",
        unit: "Ens.",
        unitPriceHT: 810.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "plo-04",
        category: "PLOMBERIE & SANITAIRES",
        designation: "Fourniture et pose receveur en céramique blanc inclus siphon de vidange L.90cm x L.90cm x P.6cm (Réf Plateforme du Bâtiment 81907)",
        unit: "U",
        unitPriceHT: 290.0,
        tvaRate: 10,
        brandRef: "Plateforme du Bâtiment",
        sourceDevis: "Devis D00207",
      },
      {
        id: "plo-05",
        category: "PLOMBERIE & SANITAIRES",
        designation: "Fourniture et pose Meuble simple vasque 2 tiroirs L.45 x H.58 x P.33 cm effet chêne naturel Remix (Réf 80125985 Leroy Merlin)",
        unit: "U",
        unitPriceHT: 480.0,
        tvaRate: 10,
        brandRef: "Remix Leroy Merlin",
        sourceDevis: "Devis D00207",
      },
      {
        id: "plo-06",
        category: "PLOMBERIE & SANITAIRES",
        designation: "Fourniture et pose mitigeur avec la barre et pomme de douche Grohe (ensemble robinet douche et barre - Réf 101926 Plateforme du Bâtiment)",
        unit: "Ens.",
        unitPriceHT: 120.0,
        tvaRate: 10,
        brandRef: "Grohe",
        sourceDevis: "Devis D00207",
      },
      {
        id: "plo-07",
        category: "PLOMBERIE & SANITAIRES",
        designation: "Fourniture et pose mitigeur lavabo Grohe EUROSMART (Réf Fabricant : 32154002)",
        unit: "U",
        unitPriceHT: 150.0,
        tvaRate: 10,
        brandRef: "Grohe Eurosmart",
        sourceDevis: "Devis D00207",
      },
      {
        id: "plo-08",
        category: "PLOMBERIE & SANITAIRES",
        designation: "Fourniture et pose toilette Pack WC à poser sortie double sans bride Compacta Sensea (Réf 70323106 Leroy Merlin)",
        unit: "U",
        unitPriceHT: 280.0,
        tvaRate: 10,
        brandRef: "Sensea Compacta Leroy Merlin",
        sourceDevis: "Devis D00207",
      },
    ],
  },
  {
    name: "REVÊTEMENTS DE SOLS & CARRELAGE",
    items: [
      {
        id: "sol-01",
        category: "REVÊTEMENTS DE SOLS & CARRELAGE",
        designation: "Fourniture et pose faïence moyenne gamme (20€TTC/m²) joints inclus sur 4 murs salle de bain (Surface : 15m², format > 20x20cm et < 80x80cm)",
        unit: "Forfait",
        unitPriceHT: 1750.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "sol-02",
        category: "REVÊTEMENTS DE SOLS & CARRELAGE",
        designation: "Fourniture et pose carrelage au sol moyenne gamme (20€TTC/m²) joints de finition inclus (salle de bain et cuisine Surface : 2,31m²)",
        unit: "Forfait",
        unitPriceHT: 1250.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "sol-03",
        category: "REVÊTEMENTS DE SOLS & CARRELAGE",
        designation: "Fourniture et pose faïence crédence cuisine moyenne gamme (20€TTC/m²) joints inclus (Surface : 3,90m²)",
        unit: "Forfait",
        unitPriceHT: 1650.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "sol-04",
        category: "REVÊTEMENTS DE SOLS & CARRELAGE",
        designation: "Application ponçage parquet avec une couche de fond dur et deux couches de vernis mat compris renforcement (couloir, séjour, chambre : 25,40m²)",
        unit: "Forfait",
        unitPriceHT: 1490.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "sol-05",
        category: "REVÊTEMENTS DE SOLS & CARRELAGE",
        designation: "Fourniture et pose parquet contrecollé. Lames de largeur 11-20 cm sur isolant phonique confort (20 dB). Pose à l'anglaise ou coupe pierre",
        unit: "m²",
        unitPriceHT: 100.0,
        tvaRate: 10,
        sourceDevis: "Devis D0192",
      },
      {
        id: "sol-06",
        category: "REVÊTEMENTS DE SOLS & CARRELAGE",
        designation: "Fourniture et pose plinthe au périphérique de l'appartement",
        unit: "m.l.",
        unitPriceHT: 8.0,
        tvaRate: 10,
        sourceDevis: "Devis D0192",
      },
      {
        id: "men-01",
        category: "REVÊTEMENTS DE SOLS & CARRELAGE",
        designation: "Fourniture et pose deux blocs-portes postformés traverse droite huisserie 88mm H.204 x L.73cm / H.204 x L.63cm (Réf 63691705 Leroy Merlin)",
        unit: "U",
        unitPriceHT: 480.0,
        tvaRate: 10,
        brandRef: "Leroy Merlin",
        sourceDevis: "Devis D00207",
      },
    ],
  },
  {
    name: "PEINTURE & FINITIONS DE SURFACE",
    items: [
      {
        id: "pei-01",
        category: "PEINTURE & FINITIONS DE SURFACE",
        designation: "PEINTURE COMPLÈTE APPARTEMENT F2 (37m² au sol) : Peinture plafond blanc mat 78, Guitte satin acrylique sur murs, blanc satin Glycéro portes/murs/plafonds SDB & cuisine. Lessivage, ouverture fissures, impression accrocheur, toile de verre, 2 couches enduit + ponçage, 2 couches peinture",
        unit: "Forfait",
        unitPriceHT: 5950.0,
        tvaRate: 10,
        sourceDevis: "Devis D00207",
      },
      {
        id: "pei-02",
        category: "PEINTURE & FINITIONS DE SURFACE",
        designation: "PEINTURE COMPLÈTE APPARTEMENT F3 67m² : Peinture plafond blanc mat 78, Guitte satin acrylique sur murs, blanc satin Glycéro SDB/Cuisine (67,8m² au sol). Lessivage, grattage, ouverture fissures, impression, ponçage/lissage, 2 couches peinture murs/plafonds, 2-3 couches boiseries",
        unit: "Forfait",
        unitPriceHT: 9800.0,
        tvaRate: 10,
        sourceDevis: "Devis D0192",
      },
    ],
  },
  {
    name: "NETTOYAGE & ENTRETIEN D'IMMEUBLES",
    items: [
      {
        id: "net-01",
        category: "NETTOYAGE & ENTRETIEN D'IMMEUBLES",
        designation: "Nettoyage immeuble 01 avec 8 appartements type F2 + immeuble 02 avec 10 appartements type F2",
        unit: "Forfait",
        unitPriceHT: 110.0,
        tvaRate: 20,
        sourceDevis: "Devis D0192 (Soliko)",
      },
      {
        id: "net-02",
        category: "NETTOYAGE & ENTRETIEN D'IMMEUBLES",
        designation: "Prestation 1 fois par semaine : Nettoyage cour et caniveau, cage d'escalier, rampe d'escalier, paliers d'escalier, hall d'entrée, porte d'entrée",
        unit: "Forfait",
        unitPriceHT: 500.0,
        tvaRate: 20,
        sourceDevis: "Devis D0192 (Soliko)",
      },
      {
        id: "net-03",
        category: "NETTOYAGE & ENTRETIEN D'IMMEUBLES",
        designation: "Prestation chaque jour sauf dimanche : Sortie des quatre conteneurs poubelles, nettoyage avec eau et produit, mise en place de sacs",
        unit: "Forfait",
        unitPriceHT: 480.0,
        tvaRate: 20,
        sourceDevis: "Devis D0192 (Soliko)",
      },
      {
        id: "net-04",
        category: "NETTOYAGE & ENTRETIEN D'IMMEUBLES",
        designation: "Prestation mensuelle : Nettoyage des fenêtres de la copropriété",
        unit: "Forfait",
        unitPriceHT: 150.0,
        tvaRate: 20,
        sourceDevis: "Devis D0192 (Soliko)",
      },
      {
        id: "net-05",
        category: "NETTOYAGE & ENTRETIEN D'IMMEUBLES",
        designation: "Nettoyage ponctuel des deux murs d'entrée (passage unique)",
        unit: "Forfait",
        unitPriceHT: 200.0,
        tvaRate: 20,
        sourceDevis: "Devis D0192 (Soliko)",
      },
    ],
  },
];
