// Données des pages /renovation-paris/paris-N, partagées avec le sitemap.

export interface ParisArrondissementData {
  number: number;
  name: string;
  postalCode: string;
  slug: string;
  neighborhoods: string[];
  architecturalStyle: string;
  description: string;
  specifics: string;
  avgPricePerSqm: string;
  beforeAfterProject: {
    beforeImage: string;
    afterImage: string;
    beforeLabel: string;
    afterLabel: string;
    title: string;
  };
  faqs: { q: string; a: string }[];
}

export const PARIS_ARRONDISSEMENTS: Record<string, ParisArrondissementData> = {
  "paris-1": {
    number: 1,
    name: "Paris 1er (Louvre / Palais-Royal)",
    postalCode: "75001",
    slug: "paris-1",
    neighborhoods: ["Palais-Royal", "Saint-Germain-l'Auxerrois", "Les Halles", "Place Vendôme"],
    architecturalStyle: "Bâtiments historiques XVIIe-XVIIIe siècles, poutres apparentes, hauteur sous plafond",
    description: "Rénovation d'appartement de prestige et pied-à-terre dans le cœur historique du 1er arrondissement de Paris.",
    specifics: "Contraintes patrimoniales strictes, rénovation de parquets anciens, modernisation des installations plomberie/électricité sans dénaturer le cachet.",
    avgPricePerSqm: "1 200 € à 1 800 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-appartement-65m2-avant.webp",
      afterImage: "/images/realisations/renovation-appartement-65m2-apres.webp",
      beforeLabel: "Avant Travaux",
      afterLabel: "Après Rénovation ERG",
      title: "Rénovation complète appartement bourgeois",
    },
    faqs: [
      { q: "Quelles sont les contraintes pour rénover dans le 1er arrondissement ?", a: "Le 1er arrondissement comporte de nombreux immeubles classés ou inscrits aux Bâtiments de France. Les travaux impactant l'extérieur ou la structure nécessitent une concertation avec l'Architecte des Bâtiments de France (ABF)." },
      { q: "Combien de temps dure un chantier de rénovation dans le 75001 ?", a: "Comptez 3 à 4 semaines pour une salle de bain ou cuisine, et 8 à 12 semaines pour la rénovation complète d'un appartement." },
    ],
  },
  "paris-2": {
    number: 2,
    name: "Paris 2e (Bourse / Montorgueil)",
    postalCode: "75002",
    slug: "paris-2",
    neighborhoods: ["Montorgueil", "Sentier", "Bonne-Nouvelle", "Gaillon"],
    architecturalStyle: "Immeubles anciens à pans de bois, lofts textiles et appartements haussmanniens",
    description: "Rénovation d'appartements et lofts dans le 2ème arrondissement de Paris, quartier dynamique et prisé.",
    specifics: "Optimisation de l'isolation phonique et thermique, redistribution des espaces dans les appartements anciens.",
    avgPricePerSqm: "1 100 € à 1 700 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Origine",
      afterLabel: "Rénové ERG",
      title: "Optimisation de surface & cuisine ouverte",
    },
    faqs: [
      { q: "Comment réussir la rénovation d'un appartement ancien dans le Sentier ?", a: "Il est primordial d'analyser l'état des planchers bois et de la structure avant de redistribution des pièces et de poser du carrelage ou du parquet." },
    ],
  },
  "paris-3": {
    number: 3,
    name: "Paris 3e (Le Marais / Temple)",
    postalCode: "75003",
    slug: "paris-3",
    neighborhoods: ["Haut-Marais", "Arts-et-Métiers", "Enfants-Rouges", "Archives"],
    architecturalStyle: "Hôtels particuliers du XVIIe siècle, ateliers et appartements typiques du Marais",
    description: "Entreprise de rénovation haut de gamme dans le 3ème arrondissement de Paris (Haut Marais).",
    specifics: "Mise en valeur de la pierre apparente, restauration de parquets de chêne et conception de salles de bain modernes.",
    avgPricePerSqm: "1 200 € à 1 900 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-salle-de-bain-3m2-avant.webp",
      afterImage: "/images/realisations/renovation-salle-de-bain-3m2-apres.webp",
      beforeLabel: "Ancienne SDB",
      afterLabel: "SDB Sur-mesure",
      title: "Création de salle de bain d'architecte",
    },
    faqs: [
      { q: "Faut-il une autorisation pour abattre une cloison dans le Marais ?", a: "Oui, si la cloison s'est avérée semi-porteuse au fil du temps ou si le syndic exige un diagnostic structure par un bureau d'études (BET)." },
    ],
  },
  "paris-4": {
    number: 4,
    name: "Paris 4e (Notre-Dame / Île Saint-Louis)",
    postalCode: "75004",
    slug: "paris-4",
    neighborhoods: ["Île Saint-Louis", "Île de la Cité", "Marais Sud", "Bastille"],
    architecturalStyle: "Bâtiments historiques d'exception, toitures Mansart, boiseries d'époque",
    description: "Rénovation d'appartements d'exception et biens d'investissement dans le 4ème arrondissement de Paris.",
    specifics: "Logistique d'accès étroite (rues historiques), protection stricte des parties communes lors des livraisons.",
    avgPricePerSqm: "1 300 € à 2 000 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-cuisine-avant.webp",
      afterImage: "/images/realisations/renovation-cuisine-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Cuisine contemporaine intégrée",
    },
    faqs: [
      { q: "Comment gérons-nous la logistique de chantier sur l'Île Saint-Louis ?", a: "Nous organisons des livraisons groupées aux heures autorisées et assurons la protection renforcée des escaliers et ascenseurs." },
    ],
  },
  "paris-5": {
    number: 5,
    name: "Paris 5e (Quartier Latin / Panthéon)",
    postalCode: "75005",
    slug: "paris-5",
    neighborhoods: ["Panthéon", "Val-de-Grâce", "Sorbonne", "Jardin des Plantes"],
    architecturalStyle: "Immeubles haussmanniens classiques et immeubles en pierre de taille",
    description: "Spécialiste de la rénovation d'appartements familiaux et studios d'étudiants dans le 5ème arrondissement.",
    specifics: "Renforcement d'isolation phonique entre étages, rénovation de parquets Point de Hongrie et moulures.",
    avgPricePerSqm: "1 000 € à 1 600 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Studio Avant",
      afterLabel: "Studio Après",
      title: "Rénovation studio Quartier Latin",
    },
    faqs: [
      { q: "Quel est le délai pour rénover un studio dans le 5ème ?", a: "Comptez environ 3 à 4 semaines de travaux intensifs clé en main." },
    ],
  },
  "paris-6": {
    number: 6,
    name: "Paris 6e (Saint-Germain-des-Prés / Luxembourg)",
    postalCode: "75006",
    slug: "paris-6",
    neighborhoods: ["Saint-Germain-des-Prés", "Odéon", "Notre-Dame-des-Champs", "Monnaie"],
    architecturalStyle: "Immeubles de grand standing, hauts plafonds sculptés, cheminées en marbre",
    description: "Rénovation intérieure sur-mesure et luxe dans le 6ème arrondissement de Paris.",
    specifics: "Prestations d'ébénisterie sur-mesure, domotique, intégration de matériaux nobles (marbre de Carrare, laiton).",
    avgPricePerSqm: "1 400 € à 2 200 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-appartement-65m2-avant.webp",
      afterImage: "/images/realisations/renovation-appartement-65m2-apres.webp",
      beforeLabel: "Origine",
      afterLabel: "Haute Précision ERG",
      title: "Rénovation d'appartement de prestige",
    },
    faqs: [
      { q: "Pouvez-vous réaliser des finitions de luxe sur-mesure ?", a: "Oui, nos équipes et partenaires artisans maîtrisent le travail du marbre, des parquets d'art et de la menuiserie intégrée." },
    ],
  },
  "paris-7": {
    number: 7,
    name: "Paris 7e (Tour Eiffel / Invalides)",
    postalCode: "75007",
    slug: "paris-7",
    neighborhoods: ["Gros-Caillou", "Invalides", "École-Militaire", "Saint-Thomas-d'Aquin"],
    architecturalStyle: "Haussmannien majestueux, immeubles pierre de taille de standing",
    description: "Rénovation complète d'appartements haussmanniens et duplex de haut standing dans le 7ème arrondissement.",
    specifics: "Rénovation énergétique avec fenêtres double vitrage bois sur-mesure agréées Bâtiments de France.",
    avgPricePerSqm: "1 300 € à 2 100 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-complete-appartement-avant.webp",
      afterImage: "/images/realisations/renovation-complete-appartement-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après Rénovation",
      title: "Rénovation complète haussmannien 110m²",
    },
    faqs: [
      { q: "Peut-on remplacer les fenêtres dans un immeuble haussmannien du 7e ?", a: "Oui, en respectant les moulures bois d'origine et la couleur imposée par le règlement de copropriété." },
    ],
  },
  "paris-8": {
    number: 8,
    name: "Paris 8e (Champs-Élysées / Madeleine)",
    postalCode: "75008",
    slug: "paris-8",
    neighborhoods: ["Madeleine", "Europe", "Faubourg-du-Roule", "Champs-Élysées"],
    architecturalStyle: "Grands appartements haussmanniens, bureaux convertis en logements",
    description: "Entreprise de rénovation TCE à Paris 8ème pour appartements d'exception et réagencement d'espaces.",
    specifics: "Création de suites parentales avec dressing et salle de bain privative, climatisation réversible encastrée.",
    avgPricePerSqm: "1 200 € à 2 000 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-salle-de-bain-3m2-avant.webp",
      afterImage: "/images/realisations/renovation-salle-de-bain-3m2-apres.webp",
      beforeLabel: "Ancienne SDB",
      afterLabel: "Suite Parentale",
      title: "Création de suite parentale moderne",
    },
    faqs: [
      { q: "Intervenez-vous pour la transformation de locaux professionnels en appartements ?", a: "Oui, nous gérons la remise aux normes complète, l'isolation et l'aménagement résidentiel." },
    ],
  },
  "paris-9": {
    number: 9,
    name: "Paris 9e (Opéra / Pigalle / Saint-Georges)",
    postalCode: "75009",
    slug: "paris-9",
    neighborhoods: ["Saint-Georges", "Rochechouart", "Chaussée-d'Antin", "Faubourg-Montmartre"],
    architecturalStyle: "Immeubles haussmanniens et style Nouvelle Athènes",
    description: "Rénovation d'appartements familiaux et lofts d'artistes dans le 9ème arrondissement de Paris.",
    specifics: "Ouverture de pièces de vie avec verrières d'atelier en acier, parquets chêne massif.",
    avgPricePerSqm: "1 100 € à 1 700 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-2-pieces-avant.webp",
      afterImage: "/images/realisations/renovation-2-pieces-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation 2 pièces avec verrière",
    },
    faqs: [
      { q: "Combien coûte une verrière sur-mesure dans un appartement du 9e ?", a: "Une verrière atelier sur-mesure en acier thermolaqué varie de 1 500 € à 3 500 € selon les dimensions et le vitrage." },
    ],
  },
  "paris-10": {
    number: 10,
    name: "Paris 10e (Canal Saint-Martin / République)",
    postalCode: "75010",
    slug: "paris-10",
    neighborhoods: ["Canal Saint-Martin", "Porte Saint-Denis", "Porte Saint-Martin", "Hôpital Saint-Louis"],
    architecturalStyle: "Anciens entrepôts, lofts et immeubles faubouriens",
    description: "Rénovation créative et optimisation d'espace dans le 10ème arrondissement de Paris.",
    specifics: "Optimisation du volume sous plafond (mezzanines), cuisines ouvertes ergonomiques.",
    avgPricePerSqm: "1 000 € à 1 550 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-cuisine-avant.webp",
      afterImage: "/images/realisations/renovation-cuisine-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation cuisine & espace de vie",
    },
    faqs: [
      { q: "Comment maximiser la lumière naturelle dans un appartement du 10e ?", a: "En déposant les cloisons non porteuses, en installant une cuisine semi-ouverte et des verrières intérieures." },
    ],
  },
  "paris-11": {
    number: 11,
    name: "Paris 11e (Bastille / Oberkampf / Nation)",
    postalCode: "75011",
    slug: "paris-11",
    neighborhoods: ["Oberkampf", "Roquette", "Sainte-Marguerite", "Folie-Méricourt"],
    architecturalStyle: "Appartements faubouriens, cour artisanales et petites copropriétés",
    description: "Entreprise de rénovation référence dans le 11ème arrondissement de Paris (Bastille & Oberkampf).",
    specifics: "Rénovation clé en main de studios, 2 pièces et 3 pièces avec optimisation poste par poste.",
    avgPricePerSqm: "1 000 € à 1 550 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Studio Origine",
      afterLabel: "Studio Rénové ERG",
      title: "Rénovation complète studio 25m² Paris 11",
    },
    faqs: [
      { q: "Quel est le prix moyen d'une rénovation complète dans le 11e ?", a: "Le budget se situe entre 900 € et 1 500 € / m² selon l'ampleur des travaux électriques, plomberie et finitions." },
    ],
  },
  "paris-12": {
    number: 12,
    name: "Paris 12e (Bercy / Daumesnil / Reuilly)",
    postalCode: "75012",
    slug: "paris-12",
    neighborhoods: ["Bel-Air", "Picpus", "Bercy", "Quinze-Vingts"],
    architecturalStyle: "Immeubles 1930, copropriétés récentes et haussmanniens de l'Est parisien",
    description: "Rénovation d'appartements familiaux et mise aux normes énergétiques dans le 12ème arrondissement.",
    specifics: "Isolation thermique intérieure (ITI), rénovation globale de salles de bain et cuisines.",
    avgPricePerSqm: "950 € à 1 450 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-salle-de-bain-3m2-avant.webp",
      afterImage: "/images/realisations/renovation-salle-de-bain-3m2-apres.webp",
      beforeLabel: "Ancienne SDB",
      afterLabel: "SDB Italienne",
      title: "Rénovation salle de bain 5m² Daumesnil",
    },
    faqs: [
      { q: "Peut-on améliorer le DPE d'un appartement dans le 12e ?", a: "Oui, par l'isolation des murs extérieurs par l'intérieur, le remplacement des fenêtres et l'installation d'une VMC performante." },
    ],
  },
  "paris-13": {
    number: 13,
    name: "Paris 13e (Gobelins / Butte-aux-Cailles / Tolbiac)",
    postalCode: "75013",
    slug: "paris-13",
    neighborhoods: ["Butte-aux-Cailles", "Maison-Blanche", "Salpêtrière", "Gare"],
    architecturalStyle: "Maisons de ville Butte-aux-Cailles, appartements récents et tours modernistes",
    description: "Rénovation d'appartements et maisons dans le 13ème arrondissement de Paris.",
    specifics: "Rénovation électrique aux normes NF C 15-100, création de douches à l'italienne étanches.",
    avgPricePerSqm: "900 € à 1 400 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-appartement-65m2-avant.webp",
      afterImage: "/images/realisations/renovation-appartement-65m2-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation appartement 4 pièces Butte-aux-Cailles",
    },
    faqs: [
      { q: "Est-il possible de créer une douche à l'italienne dans un appartement du 13e ?", a: "Oui, si la réservation dans la chape le permet ou en créant une marche technique d'accès." },
    ],
  },
  "paris-14": {
    number: 14,
    name: "Paris 14e (Montparnasse / Alésia / Denfert)",
    postalCode: "75014",
    slug: "paris-14",
    neighborhoods: ["Montparnasse", "Plaisance", "Petit-Montrouge", "Parc-de-Montsouris"],
    architecturalStyle: "Immeubles Art Déco, appartements ateliers et copropriétés pierre de taille",
    description: "Rénovation intérieure sur-mesure dans le 14ème arrondissement de Paris.",
    specifics: "Aménagement sur-mesure de placards et bibliothèques intégrées, pose de parquets chêne massif.",
    avgPricePerSqm: "950 € à 1 500 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-2-pieces-avant.webp",
      afterImage: "/images/realisations/renovation-2-pieces-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation 3 pièces Montparnasse",
    },
    faqs: [
      { q: "Quels sont les avantages d'un interlocuteur unique pour son chantier ?", a: "Un seul coordinateur gère le planning des électriciens, plombiers, peintres et menuisiers pour un respect strict des délais." },
    ],
  },
  "paris-15": {
    number: 15,
    name: "Paris 15e (Vaugirard / Grenelle / Convention)",
    postalCode: "75015",
    slug: "paris-15",
    neighborhoods: ["Saint-Lambert", "Necker", "Grenelle", "Javel"],
    architecturalStyle: "Grands ensembles familiaux, résidences de standing et haussmanniens",
    description: "Spécialiste rénovation appartement familial et cuisine équipée dans le 15ème arrondissement de Paris.",
    specifics: "Redistribution 3 et 4 pièces, création de secondes salles d'eau pour les familles.",
    avgPricePerSqm: "950 € à 1 500 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-complete-appartement-avant.webp",
      afterImage: "/images/realisations/renovation-complete-appartement-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation appartement familial 85m² Convention",
    },
    faqs: [
      { q: "Combien de temps faut-il pour rénover un 4 pièces dans le 15e ?", a: "Comptez généralement entre 6 et 10 semaines de chantier selon l'ampleur des démolitions et finitions." },
    ],
  },
  "paris-16": {
    number: 16,
    name: "Paris 16e (Auteuil / Passy / Trocadéro)",
    postalCode: "75016",
    slug: "paris-16",
    neighborhoods: ["Auteuil", "Passy", "Muette", "Porte-Dauphine"],
    architecturalStyle: "Immeubles haussmanniens d'envergure, Art Nouveau (Guimard) et pierre de taille d'exception",
    description: "Entreprise de rénovation haut de gamme d'appartements bourgeois dans le 16ème arrondissement de Paris.",
    specifics: "Restauration d'éléments d'époque (staff, moulures, dorures), salles de bain marbre et menuiserie d'art.",
    avgPricePerSqm: "1 200 € à 1 950 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-appartement-65m2-avant.webp",
      afterImage: "/images/realisations/renovation-appartement-65m2-apres.webp",
      beforeLabel: "Avant Travaux",
      afterLabel: "Après Rénovation ERG",
      title: "Rénovation d'appartement d'exception 120m² Passy",
    },
    faqs: [
      { q: "Comment préserver les moulures d'origine lors d'un doublage ou passage de câbles ?", a: "Nous réalisons des saignées techniques ciblées et faisons intervenir un staffeur pour reproduire à l'identique les ornements." },
    ],
  },
  "paris-17": {
    number: 17,
    name: "Paris 17e (Ternes / Batignolles / Monceau)",
    postalCode: "75017",
    slug: "paris-17",
    neighborhoods: ["Batignolles", "Ternes", "Plaine de Monceau", "Épinettes"],
    architecturalStyle: "Haussmannien classique (Monceau), lofts et éco-quartiers modernes (Clichy-Batignolles)",
    description: "Rénovation d'appartements et rénovations énergétiques dans le 17ème arrondissement de Paris.",
    specifics: "Conception de grandes pièces de vie ouvertes, réfection totale des peintures et revêtements.",
    avgPricePerSqm: "1 100 € à 1 750 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-2-pieces-avant.webp",
      afterImage: "/images/realisations/renovation-2-pieces-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation appartement 3 pièces Batignolles",
    },
    faqs: [
      { q: "Quelles sont les finitions de peinture conseillées ?", a: "Nous appliquons des peintures écologiques dépoussiérantes classe A+ avec impression et ponçage pour un rendu rendu parfait." },
    ],
  },
  "paris-18": {
    number: 18,
    name: "Paris 18e (Montmartre / Abbesses / Lamarck)",
    postalCode: "75018",
    slug: "paris-18",
    neighborhoods: ["Montmartre", "Goutte-d'Or", "Grandes-Carrières", "La Chapelle"],
    architecturalStyle: "Immeubles villageois, appartements sous combles et immeubles 1900",
    description: "Rénovation d'appartements à fort caractère et réagencement sur Montmartre et le 18ème arrondissement.",
    specifics: "Isolation sous toiture, aménagement de sous-pentes et création de puits de lumière.",
    avgPricePerSqm: "950 € à 1 500 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Origine",
      afterLabel: "Rénové",
      title: "Aménagement sous-comble Montmartre",
    },
    faqs: [
      { q: "Comment isoler un dernier étage sous combles ?", a: "Par une isolation en laine de roche ou panneaux sous rampant combinée à une membrane étanche à l'air." },
    ],
  },
  "paris-19": {
    number: 19,
    name: "Paris 19e (La Villette / Buttes-Chaumont)",
    postalCode: "75019",
    slug: "paris-19",
    neighborhoods: ["Buttes-Chaumont", "Villette", "Pont-de-Flandre", "Combat"],
    architecturalStyle: "Copropriétés récentes, lofts industriels et résidences verdoyantes",
    description: "Rénovation d'appartements lumineux et réagencement intérieur dans le 19ème arrondissement de Paris.",
    specifics: "Pose de parquets contrecollés chêne, rénovation complète de salles de bain familiales.",
    avgPricePerSqm: "850 € à 1 350 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-salle-de-bain-3m2-avant.webp",
      afterImage: "/images/realisations/renovation-salle-de-bain-3m2-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation salle de bain Buttes-Chaumont",
    },
    faqs: [
      { q: "Est-il possible d'ouvrir une cuisine sur le séjour ?", a: "Oui, après étude de la cloison (simple plâtre ou cloison alvéolaire) et validation technique." },
    ],
  },
  "paris-20": {
    number: 20,
    name: "Paris 20e (Belleville / Ménilmontant / Gambetta)",
    postalCode: "75020",
    slug: "paris-20",
    neighborhoods: ["Belleville", "Ménilmontant", "Père-Lachaise", "Charonne"],
    architecturalStyle: "Immeubles faubouriens, petites maisons de ville et ateliers d'artistes",
    description: "Entreprise de rénovation basée dans le 20ème arrondissement de Paris (Gambetta / Charonne).",
    specifics: "Expertise de proximité, rénovations complètes d'appartements et optimisation d'investissements.",
    avgPricePerSqm: "850 € à 1 350 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-complete-appartement-avant.webp",
      afterImage: "/images/realisations/renovation-complete-appartement-apres.webp",
      beforeLabel: "Avant Travaux",
      afterLabel: "Après Rénovation ERG",
      title: "Rénovation complète appartement Gambetta",
    },
    faqs: [
      { q: "Pourquoi choisir ERG Rénovation dans le 20e ?", a: "Nos équipes sont basées à Paris 20e (1 Sentier de la Pointe) et connaissent parfaitement le bâti et les copropriétés du secteur." },
    ],
  },
};
