export interface SuburbCityData {
  slug: string;
  name: string;
  postalCode: string;
  departmentCode: "92" | "93" | "94";
  departmentName: string;
  departmentSlug: string;
  heroTitle: string;
  metaTitle: string;
  metaDescription: string;
  neighborhoods: string[];
  architecturalStyle: string;
  description: string;
  specifics: string;
  avgPricePerSqm: string;
  beforeAfterProject: {
    beforeImage: string;
    afterImage: string;
    beforeLabel: string;
    afterLabel: string;
    title: string;
  };
  faqs: { q: string; a: string }[];
}

export const SUBURBS_DATA: Record<string, SuburbCityData> = {
  // ==========================================
  // HAUTS-DE-SEINE (92)
  // ==========================================
  "boulogne-billancourt": {
    slug: "boulogne-billancourt",
    name: "Boulogne-Billancourt",
    postalCode: "92100",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement à Boulogne-Billancourt (92100)",
    metaTitle: "Rénovation Appartement Boulogne-Billancourt (92100) | ERG Rénovation",
    metaDescription: "Entreprise de rénovation à Boulogne-Billancourt (92100) : appartement, salle de bain, cuisine. Visite sur site, devis détaillé, finitions haut de gamme.",
    neighborhoods: ["Parchamp - Le Château", "Silvy - Rives de Seine", "Point du Jour", "Trapèze", "Prince - Marmottan"],
    architecturalStyle: "Immeubles 1930 Art Déco, résidences contemporaines HQE et haussmanniens élégants",
    description: "Rénovation complète d'appartements de standing et lofts à Boulogne-Billancourt.",
    specifics: "Restauration des parquets et moulures d'époque 1930, mise aux normes électriques et optimisation des volumes de réception.",
    avgPricePerSqm: "950 € à 1 650 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-appartement-65m2-avant.webp",
      afterImage: "/images/realisations/renovation-appartement-65m2-apres.webp",
      beforeLabel: "Avant Travaux",
      afterLabel: "Après Rénovation ERG",
      title: "Rénovation complète appartement 1930 Boulogne",
    },
    faqs: [
      { q: "Quelles sont les spécificités des rénovations dans les immeubles 1930 à Boulogne ?", a: "Les immeubles 1930 nécessitent une attention particulière sur l'étanchéité des façades, le respect des huisseries d'origine et la préservation du cachet Art Déco tout en modernisant l'isolation." },
      { q: "Combien de temps faut-il pour rénover un appartement de 70m² à Boulogne-Billancourt ?", a: "Comptez 6 à 8 semaines pour une rénovation complète incluant démolition, électricité, plomberie et finitions." },
    ],
  },
  "levallois-perret": {
    slug: "levallois-perret",
    name: "Levallois-Perret",
    postalCode: "92300",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement à Levallois-Perret (92300)",
    metaTitle: "Rénovation Appartement Levallois-Perret (92300) | ERG Rénovation",
    metaDescription: "Entreprise de rénovation à Levallois-Perret (92300). Rénovation d'appartement clé en main, cuisine, salle de bain et finitions de luxe. Devis gratuit.",
    neighborhoods: ["Anatole France", "Greffulhe", "Front de Seine", "Jean Zay", "Mairie"],
    architecturalStyle: "Appartements haussmanniens récents, immeubles pierre de taille et résidences modernes",
    description: "Rénovation intérieure clé en main pour appartements familiaux et studios à Levallois-Perret.",
    specifics: "Création de cuisines semi-ouvertes avec verrière, agencement sur-mesure de dressings et suites parentales.",
    avgPricePerSqm: "1 000 € à 1 700 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-2-pieces-avant.webp",
      afterImage: "/images/realisations/renovation-2-pieces-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation 3 pièces Levallois Mairie",
    },
    faqs: [
      { q: "Gérez-vous la communication avec le syndic de copropriété à Levallois ?", a: "Oui, nous transmettons le calendrier de chantier et les fiches techniques pour assurer une intervention conforme aux règles de la copropriété." },
    ],
  },
  "courbevoie": {
    slug: "courbevoie",
    name: "Courbevoie",
    postalCode: "92400",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement à Courbevoie (92400)",
    metaTitle: "Rénovation Appartement Courbevoie (92400) | ERG Rénovation",
    metaDescription: "Spécialiste de la rénovation d'appartement à Courbevoie (Bécon, Faubourg de l'Arche, Mairie). Devis détaillé poste par poste et garantie décennale.",
    neighborhoods: ["Bécon-les-Bruyères", "Faubourg de l'Arche", "Cœur de Ville", "Gambetta"],
    architecturalStyle: "Immeubles 1900 à Bécon, résidences récentes près de La Défense",
    description: "Entreprise de rénovation TCE à Courbevoie : réagencement, isolation et finitions haut de gamme.",
    specifics: "Renforcement d'isolation phonique contre les nuisances extérieures, pose de douches à l'italienne et parquets flottants/massifs.",
    avgPricePerSqm: "900 € à 1 550 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-cuisine-avant.webp",
      afterImage: "/images/realisations/renovation-cuisine-apres.webp",
      beforeLabel: "Origine",
      afterLabel: "Rénové",
      title: "Rénovation cuisine & séjour Bécon",
    },
    faqs: [
      { q: "Quelles sont les solutions d'isolation phonique recommandées à Courbevoie ?", a: "La mise en place d'une sous-couche phonique sous parquet et le doublage acoustique des cloisons mitoyennes sont particulièrement efficaces." },
    ],
  },
  "asnieres-sur-seine": {
    slug: "asnieres-sur-seine",
    name: "Asnières-sur-Seine",
    postalCode: "92600",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation Appartement & Maison à Asnières-sur-Seine (92600)",
    metaTitle: "Rénovation Appartement Asnières-sur-Seine (92600) | ERG Rénovation",
    metaDescription: "Entreprise de rénovation à Asnières-sur-Seine. Travaux tous corps d'état pour appartements et maisons : cuisine, salle de bain, peinture, électricité.",
    neighborhoods: ["Bécon-Flachat", "Mairie", "Baco-Comète", "Grésillons", "Voltaire"],
    architecturalStyle: "Maisons 1930, meulières et appartements bourgeois en pierre de taille",
    description: "Rénovation d'appartements et maisons familiales à Asnières-sur-Seine.",
    specifics: "Réhabilitation complète, ravalement thermique et ouverture de murs porteurs (IPN) sous contrôle BET.",
    avgPricePerSqm: "850 € à 1 450 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-complete-appartement-avant.webp",
      afterImage: "/images/realisations/renovation-complete-appartement-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation complète maison & appartement Flachat",
    },
    faqs: [
      { q: "Faut-il un bureau d'études pour ouvrir un mur porteur à Asnières ?", a: "Absolument. Toute ouverture de mur porteur nécessite une étude de structure BET et la pose de fers IPN conformément à la garantie décennale." },
    ],
  },
  "colombes": {
    slug: "colombes",
    name: "Colombes",
    postalCode: "92700",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement & Maison à Colombes (92700)",
    metaTitle: "Rénovation Appartement & Maison Colombes (92700) | ERG Rénovation",
    metaDescription: "Confiez votre projet de rénovation à Colombes à ERG Rénovation. Appartements, pavillons, réfection énergétique et finitions soignées. Devis gratuit.",
    neighborhoods: ["Petite Garenne", "Centre-Ville", "Agent Sarre", "Fossés-Jean", "Wiener"],
    architecturalStyle: "Pavillons 1930, meulières et résidences collectives contemporaines",
    description: "Rénovation globale de maisons et d'appartements familiaux à Colombes.",
    specifics: "Aménagement de combles, réfection de toitures et rénovation complète d'installations électriques/plomberie.",
    avgPricePerSqm: "800 € à 1 350 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-salle-de-bain-3m2-avant.webp",
      afterImage: "/images/realisations/renovation-salle-de-bain-3m2-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Transformation Petite Garenne",
    },
    faqs: [
      { q: "Réalisez-vous l'aménagement de combles dans les pavillons de Colombes ?", a: "Oui, nous prenons en charge le renforcement de plancher, l'isolation thermique et la création de lucarnes/Velux." },
    ],
  },
  "nanterre": {
    slug: "nanterre",
    name: "Nanterre",
    postalCode: "92000",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement à Nanterre (92000)",
    metaTitle: "Rénovation Appartement Nanterre (92000) | ERG Rénovation",
    metaDescription: "Entreprise de rénovation à Nanterre (Mont-Valérien, Université, Centre). Travaux de rénovation énergétique, cuisine, salle de bain, peinture.",
    neighborhoods: ["Mont-Valérien", "Vieux-Pont", "Centre-Ville", "Parc-Nord", "Université"],
    architecturalStyle: "Résidences récentes, maisons du Mont-Valérien et immeubles collectifs",
    description: "Rénovation d'appartements et maisons à Nanterre avec optimisation budgétaire.",
    specifics: "Remise aux normes NF C 15-100, création de cloisons isolantes et aménagement de pièces d'eau.",
    avgPricePerSqm: "750 € à 1 300 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation appartement Mont-Valérien",
    },
    faqs: [
      { q: "Quel est le tarif moyen au m² pour rénover un appartement à Nanterre ?", a: "Le coût se situe entre 800 € et 1 400 € / m² selon le niveau de finitions et la complexité technique." },
    ],
  },
  "neuilly-sur-seine": {
    slug: "neuilly-sur-seine",
    name: "Neuilly-sur-Seine",
    postalCode: "92200",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement de Prestige à Neuilly-sur-Seine (92200)",
    metaTitle: "Rénovation Appartement Neuilly-sur-Seine (92200) | ERG Rénovation",
    metaDescription: "Expert en rénovation d'appartements haut de gamme à Neuilly-sur-Seine. ERG Rénovation gère votre projet de A à Z : plans, travaux, finitions de luxe.",
    neighborhoods: ["Sablons", "Bagatelle", "St-James", "Pont de Neuilly", "Charles de Gaulle"],
    architecturalStyle: "Hôtels particuliers, grands haussmanniens et résidences de très haut standing",
    description: "Rénovation d'exception et aménagement sur-mesure d'appartements à Neuilly-sur-Seine.",
    specifics: "Mise en œuvre de matériaux nobles (marbre, bois précieux, laiton), domotique intégrée et acoustique reinforced.",
    avgPricePerSqm: "1 300 € à 2 200 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-appartement-65m2-avant.webp",
      afterImage: "/images/realisations/renovation-appartement-65m2-apres.webp",
      beforeLabel: "Origine",
      afterLabel: "Prestige ERG",
      title: "Rénovation appartement 140m² Sablons",
    },
    faqs: [
      { q: "Quelles garanties offrez-vous pour les rénovations de prestige à Neuilly ?", a: "Tous nos travaux sont couverts par notre garantie décennale et assurance RC Pro. Un chef de projet unique assure le suivi hebdomadaire." },
    ],
  },
  "rueil-malmaison": {
    slug: "rueil-malmaison",
    name: "Rueil-Malmaison",
    postalCode: "92500",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation Maison & Appartement à Rueil-Malmaison (92500)",
    metaTitle: "Rénovation Maison & Appartement Rueil-Malmaison (92500) | ERG",
    metaDescription: "Entreprise de rénovation à Rueil-Malmaison. Rénovation d'appartements et maisons familiales, isolation, cuisine et salle de bain sur-mesure.",
    neighborhoods: ["Plaine-Gare", "Buzenval", "Richelieu-Châtaigneraie", "Centre-Ville", "Mont-Valérien"],
    architecturalStyle: "Belles demeures familiales, pavillons meulières et appartements modernes",
    description: "Rénovation globale de maisons et appartements à Rueil-Malmaison.",
    specifics: "Rénovation énergétique globale, aménagement de suites parentales et réhabilitation de cuisines d'exception.",
    avgPricePerSqm: "850 € à 1 450 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-complete-appartement-avant.webp",
      afterImage: "/images/realisations/renovation-complete-appartement-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après Rénovation",
      title: "Rénovation maison & appartement Buzenval",
    },
    faqs: [
      { q: "Proposez-vous des solutions d'isolation thermique pour maisons à Rueil ?", a: "Oui, nous installons des isolations par l'intérieur (ITI) et par l'extérieur (ITE) avec changement de menuiseries." },
    ],
  },
  "issy-les-moulineaux": {
    slug: "issy-les-moulineaux",
    name: "Issy-les-Moulineaux",
    postalCode: "92130",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement à Issy-les-Moulineaux (92130)",
    metaTitle: "Rénovation Appartement Issy-les-Moulineaux (92130) | ERG Rénovation",
    metaDescription: "Spécialiste de la rénovation d'appartement à Issy-les-Moulineaux (Val de Seine, Mairie, Corentin Celton). Devis gratuit et finitions soignées.",
    neighborhoods: ["Val de Seine", "Mairie d'Issy", "Corentin Celton", "Épinettes", "Ferme"],
    architecturalStyle: "Éco-quartiers modernes, immeubles 1970/1980 et résidences récentes",
    description: "Rénovation d'appartement et optimisation d'espace à Issy-les-Moulineaux.",
    specifics: "Modernisation de cuisines équipées, rénovation de salles de bain et réagencement complet 2 et 3 pièces.",
    avgPricePerSqm: "900 € à 1 500 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-cuisine-avant.webp",
      afterImage: "/images/realisations/renovation-cuisine-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation complète Val de Seine",
    },
    faqs: [
      { q: "Combien de temps prend la rénovation d'une salle de bain à Issy ?", a: "Comptez environ 2 à 3 semaines pour une réfection totale incluant dépose, plomberie et faïence." },
    ],
  },
  "suresnes": {
    slug: "suresnes",
    name: "Suresnes",
    postalCode: "92150",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement à Suresnes (92150)",
    metaTitle: "Rénovation Appartement Suresnes (92150) | ERG Rénovation",
    metaDescription: "Entreprise de rénovation à Suresnes (Cité-Jardins, Mont-Valérien, Écluse). Devis clair, respect des délais et garantie décennale.",
    neighborhoods: ["Cité-Jardins", "Mont-Valérien", "Écluse-Belvédère", "Centre-Ville"],
    architecturalStyle: "Architecture Cité-Jardins 1930, meulières et résidences récentes",
    description: "Rénovation d'appartements et maisons avec vue à Suresnes.",
    specifics: "Optimisation de lumière naturelle, réfection de parquets et modernisation de réseaux sanitaires.",
    avgPricePerSqm: "850 € à 1 400 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-2-pieces-avant.webp",
      afterImage: "/images/realisations/renovation-2-pieces-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation appartement Cité-Jardins",
    },
    faqs: [
      { q: "Quelles préconisations s'appliquent aux logements de la Cité-Jardins de Suresnes ?", a: "Il convient de respecter le caractère patrimonial des façades et des ouvertures d'origine." },
    ],
  },
  "clichy": {
    slug: "clichy",
    name: "Clichy",
    postalCode: "92100",
    departmentCode: "92",
    departmentName: "Hauts-de-Seine",
    departmentSlug: "renovation-hauts-de-seine",
    heroTitle: "Rénovation d'Appartement à Clichy (92100)",
    metaTitle: "Rénovation Appartement Clichy (92100) | ERG Rénovation",
    metaDescription: "Confiez votre rénovation d'appartement à Clichy à ERG Rénovation. Électricité, plomberie, peinture et agencement sur-mesure. Devis gratuit.",
    neighborhoods: ["Victor Hugo", "Mairie", "Bac-d'Asnières", "Entrée de Ville"],
    architecturalStyle: "Immeubles faubouriens, brique/pierre 1930 et résidences neuves",
    description: "Rénovation complète d'appartements pour résidents et investisseurs à Clichy.",
    specifics: "Démolition de cloisons, création de cuisines ouvertes et réfection complète de l'électricité.",
    avgPricePerSqm: "800 € à 1 350 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation 2 pièces Clichy Mairie",
    },
    faqs: [
      { q: "Rénovez-vous des appartements destinés au locatif à Clichy ?", a: "Oui, nous proposons des rénovations robustes et fonctionnelles parfaitement adaptées à l'investissement locatif." },
    ],
  },

  // ==========================================
  // SEINE-SAINT-DENIS (93)
  // ==========================================
  "montreuil": {
    slug: "montreuil",
    name: "Montreuil",
    postalCode: "93100",
    departmentCode: "93",
    departmentName: "Seine-Saint-Denis",
    departmentSlug: "renovation-seine-saint-denis",
    heroTitle: "Rénovation d'Appartement & Loft à Montreuil (93100)",
    metaTitle: "Rénovation Appartement & Loft Montreuil (93100) | ERG Rénovation",
    metaDescription: "Spécialiste de la rénovation d'appartements et lofts à Montreuil (Bas-Montreuil, Mairie, Signac). Devis gratuit et finitions haut de gamme.",
    neighborhoods: ["Bas-Montreuil", "Mairie de Montreuil", "Signac - Saint-Antoine", "Ruffins", "Boissière"],
    architecturalStyle: "Anciens ateliers d'artistes, lofts industriels, faubouriens et résidences neuves",
    description: "Transformation et rénovation de lofts, ateliers et appartements à Montreuil.",
    specifics: "Création de structures métalliques (verrières, mezzanines), rénovation d'isolation thermique et parquets massif.",
    avgPricePerSqm: "850 € à 1 450 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-complete-appartement-avant.webp",
      afterImage: "/images/realisations/renovation-complete-appartement-apres.webp",
      beforeLabel: "Atelier Avant",
      afterLabel: "Loft Rénové",
      title: "Transformation atelier en loft Bas-Montreuil",
    },
    faqs: [
      { q: "Comment réussir la rénovation d'un ancien atelier en loft à Montreuil ?", a: "Il faut soigner l'isolation de la toiture/verrière et valider le changement d'usage auprès de la mairie si nécessaire." },
    ],
  },
  "pantin": {
    slug: "pantin",
    name: "Pantin",
    postalCode: "93500",
    departmentCode: "93",
    departmentName: "Seine-Saint-Denis",
    departmentSlug: "renovation-seine-saint-denis",
    heroTitle: "Rénovation d'Appartement & Loft à Pantin (93500)",
    metaTitle: "Rénovation Appartement Pantin (93500) | ERG Rénovation",
    metaDescription: "Entreprise de rénovation à Pantin (Canal de l'Ourcq, Église, Quatre Chemins). Devis détaillé pour appartement, cuisine et salle de bain.",
    neighborhoods: ["Canal de l'Ourcq", "Église de Pantin", "Mairie", "Hoche", "Quatre Chemins"],
    architecturalStyle: "Bâtiments industriels réhabilités, lofts du Canal et immeubles faubouriens",
    description: "Rénovation d'appartements et lofts contemporains le long du Canal de l'Ourcq à Pantin.",
    specifics: "Aménagement d'espaces ouverts type loft, pose de béton ciré et parquets chêne.",
    avgPricePerSqm: "800 € à 1 400 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-2-pieces-avant.webp",
      afterImage: "/images/realisations/renovation-2-pieces-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation 3 pièces Canal de l'Ourcq",
    },
    faqs: [
      { q: "Intervenez-vous sur les rénovations de lofts sur les bords du Canal ?", a: "Oui, nous avons une vraie expertise sur la gestion des grands volumes et hauteurs sous plafond." },
    ],
  },
  "saint-denis": {
    slug: "saint-denis",
    name: "Saint-Denis",
    postalCode: "93000",
    departmentCode: "93",
    departmentName: "Seine-Saint-Denis",
    departmentSlug: "renovation-seine-saint-denis",
    heroTitle: "Rénovation d'Appartement à Saint-Denis (93000)",
    metaTitle: "Rénovation Appartement Saint-Denis (93000) | ERG Rénovation",
    metaDescription: "Rénovation d'appartement à Saint-Denis (Centre, Pleyel, Porte de Paris). Mise aux normes électricité, plomberie, isolation et peinture. Devis.",
    neighborhoods: ["Centre-Ville / Basilique", "Carrefour Pleyel", "Plaine Saint-Denis", "La Source"],
    architecturalStyle: "Immeubles anciens du centre historique, résidences Pleyel et logements récents",
    description: "Rénovation clé en main et remise aux normes d'appartements à Saint-Denis.",
    specifics: "Réfection complète de plomberie/électricité, traitement d'humidité et isolation acoustique.",
    avgPricePerSqm: "700 € à 1 250 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Remise à neuf appartement Pleyel",
    },
    faqs: [
      { q: "Quelles sont les normes électriques obligatoires lors d'une rénovation ?", a: "Nous appliquons strictly la norme NF C 15-100 garantissant la sécurité totale des personnes et des biens." },
    ],
  },
  "saint-ouen": {
    slug: "saint-ouen",
    name: "Saint-Ouen-sur-Seine",
    postalCode: "93400",
    departmentCode: "93",
    departmentName: "Seine-Saint-Denis",
    departmentSlug: "renovation-seine-saint-denis",
    heroTitle: "Rénovation d'Appartement à Saint-Ouen (93400)",
    metaTitle: "Rénovation Appartement Saint-Ouen (93400) | ERG Rénovation",
    metaDescription: "Spécialiste de la rénovation à Saint-Ouen (Docks, Puces, Garibaldi). Rénovation d'appartement, lofts, cuisines et salles de bain. Devis gratuit.",
    neighborhoods: ["Les Docks", "Puces de Saint-Ouen", "Garibaldi", "Mairie", "Vieux Saint-Ouen"],
    architecturalStyle: "Éco-quartier des Docks, immeubles faubouriens et lofts d'artistes",
    description: "Rénovation d'appartements et espaces atypiques à Saint-Ouen.",
    specifics: "Agencement contemporain, intégration de verrières d'atelier et cuisines sur-mesure.",
    avgPricePerSqm: "800 € à 1 400 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-cuisine-avant.webp",
      afterImage: "/images/realisations/renovation-cuisine-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation appartement Les Docks",
    },
    faqs: [
      { q: "Intervenez-vous dans le nouvel éco-quartier des Docks de Saint-Ouen ?", a: "Oui, pour la personnalisation d'appartements récents (agencement, peintures décoratives, dressing)." },
    ],
  },
  "les-lilas": {
    slug: "les-lilas",
    name: "Les Lilas",
    postalCode: "93260",
    departmentCode: "93",
    departmentName: "Seine-Saint-Denis",
    departmentSlug: "renovation-seine-saint-denis",
    heroTitle: "Rénovation d'Appartement à Les Lilas (93260)",
    metaTitle: "Rénovation Appartement Les Lilas (93260) | ERG Rénovation",
    metaDescription: "Entreprise de rénovation aux Lilas. Rénovation complète d'appartement, cuisine sur-mesure, salle de bain et peinture. Devis gratuit.",
    neighborhoods: ["Centre-Ville", "Chassagnole", "Mairie", "Sables"],
    architecturalStyle: "Petits immeubles 1930, maisons de ville et copropriétés récentes",
    description: "Rénovation chaleureuse et soignée d'appartements aux Lilas.",
    specifics: "Rénovation de parquets, agencement sur-mesure et réfection de salles d'eau.",
    avgPricePerSqm: "850 € à 1 450 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-salle-de-bain-3m2-avant.webp",
      afterImage: "/images/realisations/renovation-salle-de-bain-3m2-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation 3 pièces Les Lilas Mairie",
    },
    faqs: [
      { q: "Combien de temps dure la rénovation d'un 3 pièces aux Lilas ?", a: "Il faut prévoir environ 5 à 7 semaines pour un chantier complet clé en main." },
    ],
  },
  "aubervilliers": {
    slug: "aubervilliers",
    name: "Aubervilliers",
    postalCode: "93300",
    departmentCode: "93",
    departmentName: "Seine-Saint-Denis",
    departmentSlug: "renovation-seine-saint-denis",
    heroTitle: "Rénovation d'Appartement à Aubervilliers (93300)",
    metaTitle: "Rénovation Appartement Aubervilliers (93300) | ERG Rénovation",
    metaDescription: "Confiez vos travaux de rénovation à Aubervilliers à ERG Rénovation. Appartements, électricité, plomberie, sols et peintures. Devis gratuit.",
    neighborhoods: ["Mairie", "Quatre Chemins", "Front Populaire", "Flandre"],
    architecturalStyle: "Immeubles faubouriens, résidences récentes Front Populaire et anciens ateliers",
    description: "Rénovation et optimisation budgétaire d'appartements à Aubervilliers.",
    specifics: "Remise à neuf complète, isolation phonique et rénovation de cuisines.",
    avgPricePerSqm: "700 € à 1 200 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation appartement Front Populaire",
    },
    faqs: [
      { q: "Proposez-vous des devis détaillés gratuits à Aubervilliers ?", a: "Oui, nous réalisons une visite technique sur place et remettons un devis chiffré poste par poste sous 48h." },
    ],
  },
  "le-raincy": {
    slug: "le-raincy",
    name: "Le Raincy",
    postalCode: "93340",
    departmentCode: "93",
    departmentName: "Seine-Saint-Denis",
    departmentSlug: "renovation-seine-saint-denis",
    heroTitle: "Rénovation Appartement & Maison à Le Raincy (93340)",
    metaTitle: "Rénovation Appartement & Maison Le Raincy (93340) | ERG",
    metaDescription: "Entreprise de rénovation de haut standing au Raincy. Rénovation d'appartements bourgeois et villas. Devis personnalisé et finitions soignées.",
    neighborhoods: ["Plateau", "Thiers", "Gallieni", "Rond-Point Thiers"],
    architecturalStyle: "Villas XIXe, immeubles bourgeois pierre de taille et appartements de standing",
    description: "Rénovation de standing d'appartements bourgeois et maisons au Raincy.",
    specifics: "Restauration de staff, moulures, cheminées et parquets en chêne massif.",
    avgPricePerSqm: "850 € à 1 400 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-appartement-65m2-avant.webp",
      afterImage: "/images/realisations/renovation-appartement-65m2-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation appartement bourgeois Le Raincy",
    },
    faqs: [
      { q: "Pouvez-vous restaurer les éléments d'époque dans un appartement au Raincy ?", a: "Oui, nos menuisiers et peintres restaurent les moulures, rosaces et parquets en chêne d'origine." },
    ],
  },

  // ==========================================
  // VAL-DE-MARNE (94)
  // ==========================================
  "vincennes": {
    slug: "vincennes",
    name: "Vincennes",
    postalCode: "94300",
    departmentCode: "94",
    departmentName: "Val-de-Marne",
    departmentSlug: "renovation-val-de-marne",
    heroTitle: "Rénovation d'Appartement à Vincennes (94300)",
    metaTitle: "Rénovation Appartement Vincennes (94300) | ERG Rénovation",
    metaDescription: "Spécialiste de la rénovation d'appartement à Vincennes (Château, Bérault, Diderot). Rénovation complète, cuisine sur-mesure, finitions haut de gamme.",
    neighborhoods: ["Château", "Bérault", "Diderot", "Domaine du Bois", "Vignes"],
    architecturalStyle: "Immeubles haussmanniens élégants, pierre de taille bord de Bois et résidences 1930",
    description: "Rénovation haut de gamme d'appartements familiaux à Vincennes.",
    specifics: "Décloisonnement pour pièces de vie lumineuses, rénovation de parquets Point de Hongrie et douches italiennes.",
    avgPricePerSqm: "1 000 € à 1 750 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-complete-appartement-avant.webp",
      afterImage: "/images/realisations/renovation-complete-appartement-apres.webp",
      beforeLabel: "Avant Travaux",
      afterLabel: "Après Rénovation",
      title: "Rénovation complète haussmannien Vincennes Château",
    },
    faqs: [
      { q: "Quels sont les délais d'un chantier de rénovation complète à Vincennes ?", a: "Il faut prévoir environ 6 à 9 semaines pour la réhabilitation complète d'un appartement de 80m²." },
    ],
  },
  "saint-mande": {
    slug: "saint-mande",
    name: "Saint-Mandé",
    postalCode: "94160",
    departmentCode: "94",
    departmentName: "Val-de-Marne",
    departmentSlug: "renovation-val-de-marne",
    heroTitle: "Rénovation d'Appartement à Saint-Mandé (94160)",
    metaTitle: "Rénovation Appartement Saint-Mandé (94160) | ERG Rénovation",
    metaDescription: "Rénovation d'appartement de standing à Saint-Mandé (Bois, Tourelle, Gallieni). Matériaux nobles, finitions haut de gamme et devis sur-mesure.",
    neighborhoods: ["Bord de Bois", "Tourelle", "Gallieni", "Charles de Gaulle"],
    architecturalStyle: "Immeubles bourgeois, copropriétés de grand standing bordant le Bois de Vincennes",
    description: "Rénovation d'exception et finitions de luxe à Saint-Mandé.",
    specifics: "Intégration de boiseries sur-mesure, salles de bain en marbre et éclairages architecturaux.",
    avgPricePerSqm: "1 100 € à 1 850 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-appartement-65m2-avant.webp",
      afterImage: "/images/realisations/renovation-appartement-65m2-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation d'appartement 100m² Saint-Mandé",
    },
    faqs: [
      { q: "Travaillez-vous avec des architectes d'intérieur à Saint-Mandé ?", a: "Oui, nous pouvons exécuter les plans d'un architecte ou proposer nos propres propositions d'agencement." },
    ],
  },
  "nogent-sur-marne": {
    slug: "nogent-sur-marne",
    name: "Nogent-sur-Marne",
    postalCode: "94130",
    departmentCode: "94",
    departmentName: "Val-de-Marne",
    departmentSlug: "renovation-val-de-marne",
    heroTitle: "Rénovation Appartement & Maison à Nogent-sur-Marne (94130)",
    metaTitle: "Rénovation Maison & Appartement Nogent-sur-Marne (94130) | ERG",
    metaDescription: "Entreprise de rénovation à Nogent-sur-Marne (Baltard, Bord de Marne, Viselets). Devis gratuit pour appartements et maisons de caractère.",
    neighborhoods: ["Baltard", "Bords de Marne", "Viselets", "Le Port", "Bois-Cadet"],
    architecturalStyle: "Maisons Bords de Marne, immeubles 1930 et résidences familiales",
    description: "Rénovation d'appartements et réhabilitation de maisons à Nogent-sur-Marne.",
    specifics: "Rénovation énergétique, création de cuisines ouvertes et vérandas intégrées.",
    avgPricePerSqm: "850 € à 1 500 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-2-pieces-avant.webp",
      afterImage: "/images/realisations/renovation-2-pieces-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation maison & appartement Nogent",
    },
    faqs: [
      { q: "Quelles sont vos compétences pour la rénovation de maisons à Nogent ?", a: "Nous gérons le gros œuvre, l'isolation, la plomberie, l'électricité, la maçonnerie et toutes les finitions." },
    ],
  },
  "le-perreux-sur-marne": {
    slug: "le-perreux-sur-marne",
    name: "Le Perreux-sur-Marne",
    postalCode: "94170",
    departmentCode: "94",
    departmentName: "Val-de-Marne",
    departmentSlug: "renovation-val-de-marne",
    heroTitle: "Rénovation Appartement & Maison au Perreux-sur-Marne (94170)",
    metaTitle: "Rénovation Appartement Le Perreux-sur-Marne (94170) | ERG",
    metaDescription: "Spécialiste de la rénovation au Perreux-sur-Marne (Bords de Marne, Centre, Joullain). Devis détaillé, garantie décennale et finitions soignées.",
    neighborhoods: ["Bords de Marne", "Centre-Ville", "Joullain", "Lamartine"],
    architecturalStyle: "Belles demeures familiales, pavillons de charme et appartements de standing",
    description: "Rénovation d'intérieurs et aménagement sur-mesure au Perreux-sur-Marne.",
    specifics: "Aménagement de suites parentales, rénovation de parquets et mise aux normes thermiques.",
    avgPricePerSqm: "850 € à 1 450 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-cuisine-avant.webp",
      afterImage: "/images/realisations/renovation-cuisine-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation complète Le Perreux Centre",
    },
    faqs: [
      { q: "Proposez-vous un suivi de chantier régulier ?", a: "Oui, un compte-rendu hebdomadaire avec photos vous est envoyé par votre conducteur de travaux dédié." },
    ],
  },
  "saint-maur-des-fosses": {
    slug: "saint-maur-des-fosses",
    name: "Saint-Maur-des-Fossés",
    postalCode: "94100",
    departmentCode: "94",
    departmentName: "Val-de-Marne",
    departmentSlug: "renovation-val-de-marne",
    heroTitle: "Rénovation Maison & Appartement à Saint-Maur-des-Fossés (94100)",
    metaTitle: "Rénovation Maison & Appartement Saint-Maur (94100) | ERG",
    metaDescription: "Entreprise de rénovation à Saint-Maur-des-Fossés (Adamville, Parc, Champignol, Créteil-St-Maur). Devis pour rénovation globale d'appartement et maison.",
    neighborhoods: ["Adamville", "Le Parc", "Champignol", "La Varenne Saint-Hilaire", "Vieux Saint-Maur"],
    architecturalStyle: "Villas d'exception à La Varenne, meulières et appartements familiaux",
    description: "Rénovation globale de standing pour maisons et appartements à Saint-Maur.",
    specifics: "Rénovation de pièces de réception, suites parentales et isolation globale.",
    avgPricePerSqm: "900 € à 1 550 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-complete-appartement-avant.webp",
      afterImage: "/images/realisations/renovation-complete-appartement-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation maison La Varenne St-Hilaire",
    },
    faqs: [
      { q: "Intervenez-vous sur La Varenne Saint-Hilaire pour des rénovations lourdes ?", a: "Oui, nous réalisons des rénovations lourdes avec reprise de structure et redistribution complète." },
    ],
  },
  "creteil": {
    slug: "creteil",
    name: "Créteil",
    postalCode: "94000",
    departmentCode: "94",
    departmentName: "Val-de-Marne",
    departmentSlug: "renovation-val-de-marne",
    heroTitle: "Rénovation d'Appartement à Créteil (94000)",
    metaTitle: "Rénovation Appartement Créteil (94000) | ERG Rénovation",
    metaDescription: "ERG Rénovation modernise votre appartement à Créteil (Lac, Échat, Mairie). Projets clé en main pour un intérieur fonctionnel et esthétique. Devis gratuit.",
    neighborhoods: ["Le Lac", "L'Échat", "Mont-Mesly", "Bords de Marne", "Université"],
    architecturalStyle: "Résidences récentes modernistes, appartements du Lac et immeubles collectifs",
    description: "Rénovation d'appartements et modernisation intérieure à Créteil.",
    specifics: "Création de cuisines ouvertes, réfection électrique NF C 15-100 et douches italiennes.",
    avgPricePerSqm: "750 € à 1 250 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-salle-de-bain-3m2-avant.webp",
      afterImage: "/images/realisations/renovation-salle-de-bain-3m2-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation 4 pièces Créteil Lac",
    },
    faqs: [
      { q: "Combien coûte la réfection complète de l'électricité dans un 4 pièces à Créteil ?", a: "Comptez entre 4 500 € et 7 500 € selon le nombre de points lumineux, prises et tableau d'abonnée." },
    ],
  },
  "maisons-alfort": {
    slug: "maisons-alfort",
    name: "Maisons-Alfort",
    postalCode: "94700",
    departmentCode: "94",
    departmentName: "Val-de-Marne",
    departmentSlug: "renovation-val-de-marne",
    heroTitle: "Rénovation Appartement & Maison à Maisons-Alfort (94700)",
    metaTitle: "Rénovation Maison & Appartement Maisons-Alfort (94700) | ERG",
    metaDescription: "Rénovation complète d'appartement et maison à Maisons-Alfort (Charentonneau, Alfort, Mairie). Devis clair, finitions soignées et suivi personnalisé.",
    neighborhoods: ["Charentonneau", "Alfort", "Mairie", "Juilliottes", "Bustière"],
    architecturalStyle: "Pavillons de charme Charentonneau, immeubles 1930 et résidences calmes",
    description: "Rénovation d'appartements et pavillons familiaux à Maisons-Alfort.",
    specifics: "Optimisation de l'espace, rénovation de parquets et création de salles d'eau modernes.",
    avgPricePerSqm: "800 € à 1 350 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-studio-avant.webp",
      afterImage: "/images/realisations/renovation-studio-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après ERG",
      title: "Rénovation appartement Charentonneau",
    },
    faqs: [
      { q: "Est-il possible de refaire intégralement la plomberie d'un appartement ?", a: "Oui, nous remplaçons l'ensemble des évacuations et arrivées d'eau par des réseaux sous PER ou multicouche." },
    ],
  },
  "ivry-sur-seine": {
    slug: "ivry-sur-seine",
    name: "Ivry-sur-Seine",
    postalCode: "94200",
    departmentCode: "94",
    departmentName: "Val-de-Marne",
    departmentSlug: "renovation-val-de-marne",
    heroTitle: "Rénovation d'Appartement & Loft à Ivry-sur-Seine (94200)",
    metaTitle: "Rénovation Appartement Ivry-sur-Seine (94200) | ERG Rénovation",
    metaDescription: "Confiez votre rénovation d'appartement à Ivry-sur-Seine à ERG Rénovation. Lofts, appartements anciens, rénovation énergétique. Devis gratuit.",
    neighborhoods: ["Ivry Port", "Centre-Ville", "Petit-Ivry", "Marat-Parmentier"],
    architecturalStyle: "Anciens bâtiments industriels réhabilités, lofts et ensembles récents",
    description: "Rénovation d'appartements et lofts contemporains à Ivry-sur-Seine.",
    specifics: "Aménagement d'ateliers en lofts, isolation phonique/thermique et finitions tendances.",
    avgPricePerSqm: "750 € à 1 300 € / m²",
    beforeAfterProject: {
      beforeImage: "/images/realisations/renovation-2-pieces-avant.webp",
      afterImage: "/images/realisations/renovation-2-pieces-apres.webp",
      beforeLabel: "Avant",
      afterLabel: "Après",
      title: "Rénovation loft Ivry Port",
    },
    faqs: [
      { q: "Quels sont les avantages d'une rénovation globale à Ivry ?", a: "Elle permet de synchroniser les corps d'état, de réduire la durée totale du chantier et d'optimiser les coûts." },
    ],
  },
};
